### ISSUE TITLE
update ValveGridPos structure

### ISSUE THREAD

**Issue by dpk9** [Wyss/SLuRP#5]
old:
```yaml
  - vNum: 1
    vName: ResA
    pos:
      - 1
      - 3
```
new:
```yaml
resA:
  vNum: 1
  pos:
    - 1
    - 3
```

**Comment by dpk9** [comment]
Should do this to [master](/wyss/slurp/tree/master) branch too (in conjunction with issue #11 )

old:
```yaml
  - vNum: 12
    pos:
      - 0
      - 1
```
new:
```yaml
12:
  dPin: 40
  pos:
    - 0
    - 1
```
